import { motion } from 'framer-motion'
import { CheckCircle, Download, ArrowLeft } from 'lucide-react'

const TransferReceipt = ({ receipt, transferType, onDownload, onNewTransfer }) => {
  const formatDateTime = (isoString) => {
    const date = new Date(isoString)
    return {
      date: date.toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      }),
      time: date.toLocaleTimeString('en-US', { 
        hour: '2-digit', 
        minute: '2-digit', 
        second: '2-digit', 
        hour12: true 
      }),
      shortDate: date.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'short', 
        day: 'numeric' 
      }),
      shortTime: date.toLocaleTimeString('en-US', { 
        hour: '2-digit', 
        minute: '2-digit', 
        hour12: true 
      })
    }
  }

  const dt = formatDateTime(receipt.date)

  const downloadReceipt = () => {
    if (!receipt) return
    
    const content = `
╔══════════════════════════════════════════════════════════════════╗
║                                                                  ║
║              🏦 CREDIXA DIGITAL BANKING 🏦                       ║
║                                                                  ║
║           OFFICIAL TRANSACTION RECEIPT                           ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  REFERENCE NUMBER                                                ║
║  ${receipt.reference.padEnd(62)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  TRANSACTION DETAILS                                             ║
╠══════════════════════════════════════════════════════════════════╣
║  Status:           ${'COMPLETED ✓'.padEnd(47)} ║
║  Type:             ${(transferType === 'internal' ? 'Internal Transfer' : 'External Transfer').padEnd(47)} ║
║  Transaction ID:   ${receipt.reference.padEnd(47)} ║
║  Date:             ${dt.date.padEnd(47)} ║
║  Time:             ${dt.time.padEnd(47)} ║
║  Processing Time:  ${'Instant'.padEnd(47)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  SENDER INFORMATION                                              ║
╠══════════════════════════════════════════════════════════════════╣
║  Name:             ${receipt.senderName.padEnd(47)} ║
║  Account Number:   ${receipt.senderAccountNumber.padEnd(47)} ║
║  Bank:             ${'Credixa Banking'.padEnd(47)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  RECIPIENT INFORMATION                                           ║
╠══════════════════════════════════════════════════════════════════╣
║  Name:             ${receipt.receiverName.padEnd(47)} ║
║  Account Number:   ${(receipt.receiverAccountNumber || 'N/A').padEnd(47)} ║
║  Bank:             ${(receipt.bankName || 'Credixa Banking').padEnd(47)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  AMOUNT                                                          ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║         ${(receipt.currency + receipt.amount.toLocaleString()).padStart(35)}                    ║
║                                                                  ║
║  Amount in Words:                                                ║
║  ${receipt.currency.padEnd(62)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  ADDITIONAL INFORMATION                                          ║
╠══════════════════════════════════════════════════════════════════╣
║  Narration:        ${(receipt.narration || 'N/A').padEnd(47)} ║
║  Channel:          ${'Mobile App'.padEnd(47)} ║
║  Session ID:       ${receipt.reference.padEnd(47)} ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  This is an official receipt generated by Credixa Banking.       ║
║  Keep this receipt for your records.                             ║
║                                                                  ║
║  For support, contact: support@credixa.com                       ║
║  Generated: ${dt.shortDate} ${dt.shortTime.padEnd(37)} ║
║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Credixa-Receipt-${receipt.reference}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <motion.div key="step4" initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}>
      <div className="text-center mb-6">
        <div className="w-16 h-16 mx-auto mb-4 bg-green-500/20 rounded-full flex items-center justify-center">
          <CheckCircle className="text-green-400" size={32} />
        </div>
        <h2 className="text-2xl font-bold text-green-400">Transfer Successful!</h2>
        <p className="text-white/50 text-sm mt-1">Transaction completed securely</p>
      </div>

      <div className="bg-white/5 backdrop-blur-lg border border-white/10 rounded-2xl overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-violet-600/20 to-purple-600/20 p-4 text-center border-b border-white/10">
          <div className="w-10 h-10 mx-auto mb-2 bg-gradient-to-br from-violet-500 to-pink-500 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-lg">C</span>
          </div>
          <h3 className="font-bold">CREDIXA BANKING</h3>
          <p className="text-white/50 text-xs">Official Transaction Receipt</p>
        </div>

        <div className="p-4 space-y-3">
          {/* Reference */}
          <div className="bg-white/5 rounded-lg p-3">
            <p className="text-white/40 text-xs uppercase tracking-wider">Reference Number</p>
            <p className="font-mono font-semibold text-sm text-violet-400">{receipt.reference}</p>
          </div>

          {/* Status & Type */}
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-white/5 rounded-lg p-3">
              <p className="text-white/40 text-xs uppercase tracking-wider">Status</p>
              <p className="text-green-400 font-bold text-sm flex items-center gap-1">
                <CheckCircle size={14} /> SUCCESSFUL
              </p>
            </div>
            <div className="bg-white/5 rounded-lg p-3">
              <p className="text-white/40 text-xs uppercase tracking-wider">Type</p>
              <p className="text-sm">{transferType === 'internal' ? 'Internal Transfer' : 'External Transfer'}</p>
            </div>
          </div>

          {/* Date & Time */}
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-white/5 rounded-lg p-3">
              <p className="text-white/40 text-xs uppercase tracking-wider">Date</p>
              <p className="text-sm">{dt.date}</p>
            </div>
            <div className="bg-white/5 rounded-lg p-3">
              <p className="text-white/40 text-xs uppercase tracking-wider">Time</p>
              <p className="text-sm">{dt.time}</p>
            </div>
          </div>

          {/* Sender */}
          <div className="bg-white/5 rounded-lg p-3">
            <p className="text-white/40 text-xs uppercase tracking-wider mb-2">From</p>
            <p className="font-semibold text-sm">{receipt.senderName}</p>
            <p className="text-xs text-white/50">{receipt.senderAccountNumber}</p>
            <p className="text-xs text-white/50">Credixa Banking</p>
          </div>

          {/* Recipient */}
          <div className="bg-white/5 rounded-lg p-3">
            <p className="text-white/40 text-xs uppercase tracking-wider mb-2">To</p>
            <p className="font-semibold text-sm">{receipt.receiverName}</p>
            <p className="text-xs text-white/50">{receipt.receiverAccountNumber || 'N/A'}</p>
            <p className="text-xs text-white/50">{receipt.bankName || 'Credixa Banking'}</p>
          </div>

          {/* Amount */}
          <div className="bg-gradient-to-r from-violet-600/10 to-purple-600/10 rounded-xl p-4 text-center border border-violet-500/20">
            <p className="text-white/40 text-xs uppercase tracking-wider mb-1">Amount Transferred</p>
            <p className="text-3xl font-bold text-white">{receipt.currency}{receipt.amount.toLocaleString()}</p>
          </div>

          {/* Narration */}
          {receipt.narration && (
            <div className="bg-white/5 rounded-lg p-3">
              <p className="text-white/40 text-xs uppercase tracking-wider">Narration</p>
              <p className="text-sm">{receipt.narration}</p>
            </div>
          )}

          {/* Session Info */}
          <div className="bg-white/5 rounded-lg p-3">
            <p className="text-white/40 text-xs uppercase tracking-wider">Session ID</p>
            <p className="font-mono text-xs text-white/60">{receipt.reference}</p>
          </div>
        </div>

        <div className="p-3 border-t border-white/10 text-center">
          <p className="text-xs text-white/40">Thank you for banking with Credixa</p>
          <p className="text-xs text-white/30 mt-1">For support: support@credixa.com</p>
        </div>
      </div>

      <div className="flex gap-3 mt-4">
        <button 
          onClick={downloadReceipt}
          className="flex-1 py-3 border border-violet-600 text-violet-400 rounded-xl font-semibold flex items-center justify-center gap-2 hover:bg-violet-600/10 text-sm"
        >
          <Download size={16} /> Download Receipt
        </button>
        <button 
          onClick={onNewTransfer}
          className="flex-1 py-3 bg-gradient-to-r from-violet-600 to-purple-600 rounded-xl text-white font-bold text-sm"
        >
          New Transfer
        </button>
      </div>
    </motion.div>
  )
}

export default TransferReceipt
